# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/3.25.0/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/3.25.0/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/3.25.0/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/_deps/doctest-src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/_deps/doctest-src/scripts/cmake/Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/CMakeUtils/files_and_folders.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/exe_path/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glfw/CMake/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glfw/CMake/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glfw/docs/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glfw/docs/Doxyfile.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glpp-extended/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glpp-extended/lib/glm/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glpp-extended/lib/glm/cmake/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glpp-extended/lib/glm/glm/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/glpp-extended/lib/glpp/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/img/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/imgui/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/lib/p6/third-party/op/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FetchContent.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FetchContent/CMakeLists.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FindDoxygen.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FindGit.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Apple-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Apple-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Apple-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.25.0/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -P /Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/VerifyGlobs.cmake

/Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -H/Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1 -B/Users/liloualidor/documents/IMAC/annee_2/POO/S4/p6_1/build-xcode
